### ISSUE TITLE
Semester Project Feedback

### ISSUE THREAD

**Issue by Rachel-Veenstra** [KaynRyu/semesterProject#3]
Hi Brett,

Your project is something that is completely out of my wheelhouse, which was both daunting and intriguing as I looked through your repository. Your files were well-named and easy to find, which made my "digging" a lot more simple to do. :)

Here are a few comments I have regarding your repository:

**Requirements File:**
> I thought this was a great addition to your repository. I noticed that Adrian was not able to run your code either, but I know that I do not have the necessary programs to do so. The requirements list would help avoid this problem for anyone trying to use your code in your lab or elsewhere. Great idea!

**Examples for Clarification:**
> Because this topic was foreign to me and I had never heard of several of the modules you were using, I found myself lost at a few steps, especially because I could not run your code. Displaying a "step-by-step" approach in different cells and printing out intermediate outputs using a .ipynb file would probably be more useful and easy to follow for someone with no knowledge of your topic. While it takes up more room and looks less clean, I think having a code like this, or even adding an additional copy of your code for "instructional" purposes would be very nice.

**White Space:**
> While your code looked very clean and condensed, adding more white space would be more "aesthetically" pleasing to users. Perhaps this could be a component of the "instructional" copy I suggested, and your hard code could be kept the same.

**Input/Output/Author/Created Documentation:**
> My last comment is that additional documentation on the requirements and location for inputs, the characteristics and location of outputs, and general author/date information would be beneficial to users and also ensure that you are getting credit for all of the hard work you've put into this project! :) Adding the date could also be beneficial for keeping track of when the code was last updated and documenting changes between different versions of your code as it continues to be adapted to the needs of your lab environment.

Overall, I thought you did a great job organizing everything, and, while I could not successfully run your code, it seemed to accomplish your specific goals in a logical way.

Great job!
Rachel

**Comment by KaynRyu** [comment]
Thank you for the feedback, I will definitely upload an instructional IPython notebook for this program, as to Adrians issue,  I have also included a How-To section for getting setup to run this program in the ReadMe which I will most likely create a Wiki for to make it a bit easier to use. 
I really appreciate the help and i know a big issue for most scientists no matter the subject matter is communication. I will make sure to work on this in the future.
